<?php

namespace AppBundle\Repository;

/**
 * FavouriteStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteStoryRepository extends \Doctrine\ORM\EntityRepository
{
}
