<?php

namespace AppBundle\Repository;

/**
 * FavouriteSnippetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteSnippetRepository extends \Doctrine\ORM\EntityRepository
{
}
