<?php

namespace AppBundle\Repository;

/**
 * SnippetStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
