<?php

namespace AppBundle\Repository;

/**
 * SnippetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetRepository extends \Doctrine\ORM\EntityRepository
{
}
