# base url
base_url:
  path:     /
  defaults: { _controller: AppBundle:Default:index }
  methods:  [GET]

# logout
logout:
    path: /logout

snippets:
    resource: "routing/snippet_routing.yml"

stories:
    resource: "routing/story_routing.yml"

projects:
    resource: "routing/project_routing.yml"

