
# base url
base_url:
  path:     /
  defaults: { _controller: AppBundle:Default:index }
  methods:  [GET]

# Story actions
story_index:
  path:     /story
  defaults: { _controller: AppBundle:Story:index }
  methods:  [GET]
story_new:
  path:     /story/new
  defaults: { _controller: AppBundle:Story:new }
  methods:  [GET, POST]
story_show:
  path:     /story/{id}/show
  defaults: { _controller: AppBundle:Story:show }
  methods:  [GET]
  requirements:
      id:     \d+      
story_edit:
  path:     /story/{id}/edit
  defaults: { _controller: AppBundle:Story:edit}
  methods:  [GET, POST]
  requirements:
      id:     \d+      
story_delete:
  path:     /story/{id}/delete
  defaults: { _controller: AppBundle:Story:delete }
  methods:  [DELETE]
  requirements:
      id:     \d+      

# Snippet actions
snippet_index:
  path:     /snippet
  defaults: { _controller: AppBundle:Snippet:index }
  methods:  [GET]
snippet_new:
  path:     /story/{id}/snippet/new
  defaults: { _controller: AppBundle:Snippet:new }
  methods:  [GET, POST]
snippet_show:
  path:     /snippet/{id}/show
  defaults: { _controller: AppBundle:Snippet:show }
  methods:  [GET]
  requirements:
      id:     \d+      
snippet_edit:
  path:     /snippet/{id}/edit
  defaults: { _controller: AppBundle:Snippet:edit}
  methods:  [GET, POST]
  requirements:
      id:     \d+      
snippet_delete:
  path:     /snippet/{id}/delete
  defaults: { _controller: AppBundle:Snippet:delete }
  methods:  [DELETE]
  requirements:
      id:     \d+      

# logout
logout:
    path: /logout

